joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 20

diff_drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: 'wheel_left_joint'
  right_wheel: 'wheel_right_joint'
  pose_covariance_diagonal:  [0.05, 0.05, 1000000.0, 1000000.0, 1000000.0, 1.5]
  twist_covariance_diagonal: [0.05, 0.05, 1000000.0, 1000000.0, 1000000.0, 1.5]
  wheel_separation: 0.175
  wheel_radius: 0.035525
  base_frame_id: 'base_footprint'
  # Odometry fused with IMU is published by robot_localization, so
  # no need to publish a TF based on encoders alone.
  enable_odom_tf: false
  publish_rate: 20
  cmd_vel_timeout: 3.0
