## USB port
port: /dev/razorIMU


##### Calibration ####
### accelerometer
accel_x_min: -285
accel_x_max: 280
accel_y_min: -293
accel_y_max: 273
accel_z_min: -298
accel_z_max: 218

### magnetometer
# standard calibration
magn_x_min: -259
magn_x_max: 848
magn_y_min: -448
magn_y_max: 565
magn_z_min: -954
magn_z_max: 150


# extended calibration
calibration_magn_use_extended: true
magn_ellipsoid_center: [-70.5973, 159.151, -546.588]
magn_ellipsoid_transform: [[0.789855, -0.0172841, 0.0229592], [-0.0172841, 0.831006, -0.00541975], [0.0229592, -0.00541975, 0.997173]]

# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: -25.75
gyro_average_offset_y: -34.64
gyro_average_offset_z: -11.09
